name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - run: bunx prisma generate --schema packages/prisma/prisma/schema.prisma

      - run: bunx nx format:check --base="remotes/origin/main"

      - run: bunx nx run-many -t lint build typecheck test
